# PyTorch Tensors

This notebook contains operations on PyTorch Tensors. 

In [2]:
# Import torch
import torch as T

In [9]:
# Create tensors of various dimensions
points = T.zeros(6)
print(points)
points = T.ones(4)
print(points)

tensor([0., 0., 0., 0., 0., 0.])
tensor([1., 1., 1., 1.])


In [10]:
# Set/Get value by indexing
points[0] = 5
points[1] = 2
points[3] = 7

print(points[2])

tensor(1.)


In [16]:
# create tensor containing 3 2D points
lst = [[2,0], [5,0], [3,2]]
points = torch.tensor(lst)


In [18]:
# index tensor in various ways
print(points[2])
print(points[1,1])
print(points[:,1])

tensor([3, 2])
tensor(0)
tensor([0, 0, 2])


In [20]:
# Get tensor shape, type
points.shape
points.type

<function Tensor.type>

In [22]:
# Populate tensor with random values
img = torch.randn(3, 5, 5)
img

tensor([[[-2.6489,  0.8136,  0.2038, -0.8964,  1.9363],
         [-0.4548,  0.7706, -1.0555,  0.4950, -0.1613],
         [-0.3261, -0.0993,  0.3406, -1.0485,  0.0795],
         [ 0.9644, -1.1222, -0.9037, -1.2191,  1.1530],
         [ 0.5329, -0.2331,  0.5353,  1.8807,  1.4491]],

        [[ 0.6852, -0.4305, -0.0890, -0.3706,  0.2255],
         [ 1.7558,  1.7212,  1.3999,  1.1688,  1.2477],
         [ 0.5138, -1.1574, -2.4154,  1.2857, -0.0141],
         [-0.1958, -0.5426,  0.8890,  0.8756, -0.1843],
         [ 0.3559, -1.3783, -0.6964, -0.9715, -0.6995]],

        [[ 0.3027,  0.5659,  0.6285,  1.5689, -1.5820],
         [-0.7026,  0.7048,  1.0274,  1.0822, -0.2537],
         [-1.2240, -0.0240, -0.4714,  0.7157,  0.4574],
         [-0.3134,  0.2260, -1.3199, -1.1348,  0.3237],
         [ 0.6128, -0.1506,  0.6510,  0.2084, -1.2175]]])

In [23]:
# Create a batch of 4 RGB images
# [batch, channels, rows, columns]
batch = T.randn(4, 3, 5, 5)

# Compute average image cross RGB channels by averaging the last 3 axes
img_avg = batch.mean(-3)
# 4 5x5 images. 
img_avg.shape

torch.Size([4, 5, 5])

In [25]:
"""
Naming tensors.

We can name the dimensions of a tensor with names to 
avoid errors when accessing them.
** Currently an experimental feautre. 

"""
weights_named = T.tensor([0.343, 0.4213], names=['channels'])
weights_named

C:\Users\Kyle\Anaconda3\envs\rl\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:840.)
  


tensor([0.3430, 0.4213], names=('channels',))

In [ ]:
#